services:
  apache:
    image: httpd:latest
    container_name: apache_server
    ports:
      - "8080:80"
    volumes:
      - ./www:/usr/local/apache2/htdocs/
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
